services:
  postgres:
    build:
      context: .
      dockerfile: "Dockerfile"
    container_name: postgres-wal-g
    ports:
      - "6050:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data  
